Update the templates package.json to patch for vulnerability in dependency
grommet/grommet-cli pull request #55
Opened 2018-06-08 08:06 UTC by corysolovewicz

Update node-sass version to 4.9.0 since 4.1.1 depended on  a vulnerable version of hoek node module which suffers from a (MAID) vulnerability.  see https://nvd.nist.gov/vuln/detail/CVE-2018-3728 for more information.

2018-06-11 05:42 UTC, alansouzati commented on src/utils/cli.js
> +  hpinc: 'grommet/scss/dxc/index'
should this say `dxc` in the hey?

2018-06-11 05:43 UTC, alansouzati commented on templates/app/package.json
> +    "node-sass": "^4.9.0",
`^4.1.1` should pick up `4.9.0`. But I like the explicitness of this change.

2018-06-11 05:44 UTC, alansouzati requested changes
This looks good to me. thanks for the contribution. I believe you should change `hpinc` to `dxc` in the object key

2018-06-12 16:20 UTC, merged

2018-06-12 17:10 UTC, corysolovewicz commented
Thanks for the merge Alan!